Added Kensei
tbltp/tabletop pull request #58
Opened 2020-12-10 04:54 UTC by JohnathanShiao

2020-12-10 04:58 UTC, TresTres requested changes
please account for the weapon proficiency

2020-12-11 17:48 UTC, JohnathanShiao commented
fixed weapon proficiencies

2020-12-17 06:09 UTC, TresTres requested changes

2020-12-17 06:09 UTC, TresTres commented on src/Classes/Monk/Subclasses/Kensei/Kensei.json
> +<<<<<<< HEAD
You have some artifacts like this from merging that shouldn't be here

2020-12-17 06:09 UTC, TresTres commented on src/Classes/Monk/Subclasses/MonkSubclass.ts
> +<<<<<<< HEAD
in this file too

2021-01-23 01:18 UTC, alimohamad approved these changes
10/10

2021-01-23 01:22 UTC, merged